{% set name = "melody" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yoav-lavi/melody/archive/{{ version }}.tar.gz
  sha256: d7605160d3589578c84a919c09addd8f4bd1f06441795192041b491462c9f655

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - melody --help

about:
  home: https://yoav-lavi.github.io/melody/book
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Language that compiles to regular expressions
  dev_url: https://github.com/yoav-lavi/melody

extra:
  recipe-maintainers:
    - danielnachun
